# 1. 프로젝트 이름 (교재 이름에서 우리 프로젝트명으로 변경)
spring.application.name=chargerReservation

# UTF-8 : 한글 설정: shift 키 2번 -> 돋보기: 인코딩 -> 프로퍼티~인코딩 클릭 -> UTF-8 선택, 체크 -> 확인 버튼 클릭

# 2. Oracle DB Setting (팀장님 PC의 오라클 설정 그대로 유지)
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=scott
spring.datasource.password=!Ds1234567890

# 3. JPA Setting (그대로 유지)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# 4. File Upload Setting (그대로 유지)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
image.upload-dir=c:/Work/upload/

# 5. Error Messages Setting (그대로 유지)
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# 6. React IP Setting (프론트엔드 포트 5173 그대로 유지)
spring.react.ip=http://localhost:5173

# 7. Redis Setting (리프레시 토큰 & 현장 핀번호 저장용)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# 8. JWT Token Setting (로그인 보안용)
# 주의: secret-key는 무조건 32바이트(글자) 이상이어야 작동합니다. (아래는 예시)
jwt.secret-key=TeamprojectElectricVehicleReservationSystemSecretKey2026
# Access Token 만료 시간 (예: 30분 = 1800000 밀리초)
jwt.access-token-validity-in-milliseconds=1800000
# Refresh Token 만료 시간 (예: 7일 = 604800000 밀리초)
jwt.refresh-token-validity-in-milliseconds=604800000