# OAuth2 키 관리
spring.security.oauth2.client.registration.naver.client-id=발급받은_Client_ID
spring.security.oauth2.client.registration.naver.client-secret=발급받은_Client_Secret

spring.security.oauth2.client.registration.kakao.client-id=발급받은_REST_API_키
spring.security.oauth2.client.registration.kakao.client-secret=발급받은_Client_Secret


# ... 기존 OAuth2 설정들 ...

# 10. Spring Mail (이 내용을 추가해야 에러가 사라집니다!)
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=본인의네이버아이디@naver.com
spring.mail.password=네이버_2단계인증_앱비밀번호
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com

# 11. SOLAPI (문자 발송 설정도 같이 들어있어야 안전합니다)
solapi.api-key=NCSKU6ZTCVFFUMTG
solapi.api-secret=JTUW68ONV32JEUVB4AINMFT5HECYLN2O
solapi.from-number=01034441086