# OAuth2 키 관리
spring.security.oauth2.client.registration.naver.client-id=발급받은_Client_ID
spring.security.oauth2.client.registration.naver.client-secret=발급받은_Client_Secret

spring.security.oauth2.client.registration.kakao.client-id=발급받은_REST_API_키
spring.security.oauth2.client.registration.kakao.client-secret=발급받은_Client_Secret