# OAuth2 키 관리
spring.security.oauth2.client.registration.naver.client-id=aWa6azBVuw_druD23BAO
spring.security.oauth2.client.registration.naver.client-secret=v3V7Y4owt_

spring.security.oauth2.client.registration.kakao.client-id=1c9cf0acc2f4c9185dbcba71f5cb437c
spring.security.oauth2.client.registration.kakao.client-secret=3LKCBrS5871Nif0o7tRRhibhKsWOb1jf


# Mail Server 설정
spring.mail.username=peb7949@naver.com
spring.mail.password=V8YRRZH5K6UN
